# Datasource - PostgreSQL (el del docker-compose de cyberstream-infra)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=cyberstream
quarkus.datasource.password=cyberstream
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cyberstream
quarkus.hibernate-orm.schema-management.strategy=update

# Kafka - consumer del topic network.metrics
mp.messaging.incoming.network-metrics.connector=smallrye-kafka
mp.messaging.incoming.network-metrics.topic=network.metrics
mp.messaging.incoming.network-metrics.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.bootstrap.servers=localhost:9092

quarkus.http.port=8080
quarkus.http.host=0.0.0.0

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://cyberstream.local/issuer
smallrye.jwt.sign.key.location=privateKey.pem